# -*- coding: utf-8 -*-
"""text to speech

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ApMhaTmfOy88_Xjt1e1eEa8WTvW2W-cs
"""

!pip install gTTS

from gtts import gTTS
from IPython.display import Audio

# Input text to be converted to spee
text ="dr.neelima madam works as a assiatant professor in acharya nagarjuna university
# Convert the text to speech
tts = gTTS(text)

# Save the audio as an mp3 file
tts.save("output.mp3")

# Play the audio in Colab
Audio("output.mp3")

from google.colab import files
files.download("output.mp3")